// withAsyncStorageDbSize — raises the Android AsyncStorage SQLite ceiling.
//
// WHY THIS EXISTS (data-perf audit, 2026-08-06):
// @react-native-async-storage/async-storage caps its Android database at 6 MB by
// default (see node_modules/.../android/config.gradle → getDatabaseSize). Our
// persisted React Query cache measured 5.66 MB at 4,300 saved words — 94% of
// that cap — and the cache scales with library size.
//
// The failure past the cap is what makes this worth a plugin rather than a
// backlog note: `setItem` throws, react-query-persist-client swallows the
// rejection into its retry path (we configure no `retry` handler), and the app
// simply stops persisting. No crash, nothing in the logs, no user-visible
// error — it surfaces weeks later as "offline mode stopped working" on exactly
// the power users whose libraries got big enough to trip it.
//
// Filtering what we persist (src/query/queryClient.ts → shouldDehydrateQuery)
// is the real fix and brings the blob well back under the default. This plugin
// is the belt to that suspenders: it removes the INVISIBLE-failure cliff so a
// future regression in what we cache degrades loudly instead of silently.
//
// WHY A PLUGIN AND NOT android/gradle.properties: `android/` is gitignored
// (.gitignore:43) because it is generated by `expo prebuild`. An edit there is
// untracked and is destroyed by the next `--clean` prebuild. Config plugins are
// the only durable way to reach the native project — same reason
// withAndroidLocaleConfig exists.
//
// The value is a MAXIMUM, not an allocation: SQLite grows to fit and the number
// only bounds how far it may grow.
const { withGradleProperties } = require('@expo/config-plugins');

const PROPERTY = 'AsyncStorage_db_size_in_MB';

/** 50 MB: ~10× the measured 4.3k-word blob, so it clears any realistic library
 *  (the cap is per-user-device, and the biggest fixture we model is 4,300 words)
 *  without being so large that a runaway cache could fill a device unnoticed. */
const DEFAULT_SIZE_MB = 50;

module.exports = function withAsyncStorageDbSize(config, { sizeMB = DEFAULT_SIZE_MB } = {}) {
  return withGradleProperties(config, (cfg) => {
    // Replace rather than append — prebuild may run against an existing
    // gradle.properties, and a duplicate key is resolved last-one-wins by
    // Gradle, which would make the effective value depend on file order.
    cfg.modResults = cfg.modResults.filter(
      (item) => !(item.type === 'property' && item.key === PROPERTY),
    );
    cfg.modResults.push({
      type: 'comment',
      value: `AsyncStorage ceiling raised from the 6 MB default — see plugins/withAsyncStorageDbSize.js`,
    });
    cfg.modResults.push({
      type: 'property',
      key: PROPERTY,
      value: String(sizeMB),
    });
    return cfg;
  });
};
