// AUTO-GENERATED by scripts/sync-tokens.mjs — DO NOT EDIT.
// Source of truth: lexicamp-design-system/project/tokens/*.css
// Regenerate:  node scripts/sync-tokens.mjs
/* eslint-disable */

export const tokens = {
  "palette": {
    "blue": {
      "50": "#eef4f8",
      "100": "#d7e6f0",
      "200": "#aecde0",
      "300": "#80b1cc",
      "400": "#5491b5",
      "500": "#3c7499",
      "600": "#2f5e7e",
      "700": "#264c66",
      "800": "#1f3d52",
      "900": "#182f3f"
    },
    "green": {
      "50": "#eaf3ed",
      "100": "#cde6d6",
      "200": "#a0d0b3",
      "300": "#6fb78d",
      "400": "#459a6b",
      "500": "#2e7d52",
      "600": "#246541",
      "700": "#1d5135",
      "800": "#173f29",
      "900": "#11301f"
    },
    "amber": {
      "50": "#fff5ed",
      "100": "#fde5cc",
      "200": "#fac899",
      "300": "#f7a855",
      "400": "#f48d2a",
      "500": "#e87722",
      "600": "#c85a1a",
      "700": "#a04412",
      "800": "#78330d",
      "900": "#552409"
    },
    "slate": {
      "50": "#f7f9fa",
      "100": "#eef1f3",
      "200": "#dde3e8",
      "300": "#c2cdd4",
      "400": "#9aa8b2",
      "500": "#71808b",
      "600": "#54616b",
      "700": "#3e4951",
      "800": "#2a333a",
      "900": "#182026"
    },
    "red": {
      "100": "#f7dadd",
      "500": "#d1495b",
      "600": "#af3848"
    },
    "pika": {
      "50": "#fffbea",
      "100": "#fff3c0",
      "200": "#ffe480",
      "300": "#ffcd45",
      "400": "#f5b91e",
      "500": "#e9a52a",
      "600": "#c47830",
      "700": "#9a5820",
      "800": "#6e3c10",
      "900": "#4a2608"
    }
  },
  "color": {
    "brand": "#3c7499",
    "brandStrong": "#2f5e7e",
    "brandSoft": "#d7e6f0",
    "brandTint": "#eef4f8",
    "onBrandSoft": "#264c66",
    "accent": "#e87722",
    "accentSoft": "#fde5cc",
    "accentTint": "#fff5ed",
    "accentStrong": "#a04412",
    "accentCta": "#e87722",
    "textOnAccentCta": "#ffffff",
    "evergreen": "#2e7d52",
    "evergreenSoft": "#cde6d6",
    "evergreenTint": "#eaf3ed",
    "onSuccessSoft": "#1d5135",
    "canvas": "#f7f9fa",
    "surfaceCard": "#ffffff",
    "surfaceSunken": "#eef1f3",
    "surfaceInverse": "#1f3d52",
    "textStrong": "#182026",
    "textBody": "#3e4951",
    "textMuted": "#54616b",
    "textFaint": "#9aa8b2",
    "textOnBrand": "#ffffff",
    "textOnAccent": "#182026",
    "textOnDanger": "#ffffff",
    "textLink": "#2f5e7e",
    "border": "#dde3e8",
    "borderStrong": "#c2cdd4",
    "divider": "#eef1f3",
    "success": "#2e7d52",
    "successSoft": "#cde6d6",
    "warning": "#e87722",
    "warningSoft": "#fde5cc",
    "danger": "#af3848",
    "dangerSoft": "#f7dadd",
    "info": "#3c7499",
    "infoSoft": "#d7e6f0",
    "pikaGolden": "#ffcd45",
    "focusRing": "rgba(60, 116, 153, 0.45)",
    "overlayScrim": "rgba(24, 47, 63, 0.45)",
    "overlayDark": "rgba(24, 47, 63, 0.72)",
    "overlayGlass": "rgba(255, 255, 255, 0.82)",
    "overlayTint": "rgba(60, 116, 153, 0.06)",
    "skeletonBase": "#eef1f3",
    "skeletonShine": "#dde3e8"
  },
  "font": {
    "family": {
      "serif": "Spectral",
      "sans": "Plus Jakarta Sans",
      "mono": "Space Mono"
    },
    "size": {
      "2xs": 11,
      "xs": 12,
      "sm": 14,
      "md": 16,
      "lg": 18,
      "xl": 21,
      "2xl": 26,
      "3xl": 32,
      "4xl": 40,
      "5xl": 52,
      "6xl": 64
    },
    "weight": {
      "regular": "400",
      "medium": "500",
      "semibold": "600",
      "bold": "700",
      "extra": "800"
    },
    "leading": {
      "tight": 1.12,
      "snug": 1.28,
      "normal": 1.5,
      "relaxed": 1.7
    },
    "tracking": {
      "tight": -0.02,
      "normal": 0,
      "wide": 0.04,
      "caps": 0.08
    }
  },
  "space": {
    "0": 0,
    "1": 4,
    "2": 8,
    "3": 12,
    "4": 16,
    "5": 20,
    "6": 24,
    "8": 32,
    "10": 40,
    "12": 48,
    "16": 64,
    "20": 80
  },
  "radius": {
    "xs": 6,
    "sm": 10,
    "md": 14,
    "lg": 20,
    "xl": 28,
    "2xl": 36,
    "pill": 999
  },
  "borderWidth": {
    "thin": 1,
    "base": 1.5,
    "thick": 2
  },
  "shadow": {
    "xs": "0 1px 2px rgba(24, 47, 63, 0.06)",
    "sm": "0 2px 6px rgba(24, 47, 63, 0.07)",
    "md": "0 6px 16px rgba(24, 47, 63, 0.09)",
    "lg": "0 14px 32px rgba(24, 47, 63, 0.12)",
    "xl": "0 24px 56px rgba(24, 47, 63, 0.16)",
    "inset": "inset 0 1px 3px rgba(24, 47, 63, 0.10)",
    "brand": "0 8px 20px rgba(60, 116, 153, 0.28)",
    "accent": "0 8px 20px rgba(217, 142, 24, 0.28)"
  },
  "motion": {
    "easing": {
      "out": "cubic-bezier(0.22, 1, 0.36, 1)",
      "inOut": "cubic-bezier(0.65, 0, 0.35, 1)",
      "spring": "cubic-bezier(0.34, 1.56, 0.64, 1)"
    },
    "duration": {
      "fast": 120,
      "base": 220,
      "slow": 380
    },
    "z": {
      "base": 1,
      "sticky": 100,
      "overlay": 1000,
      "toast": 1200
    }
  },
  "colorDark": {
    "brand": "#3c7499",
    "brandStrong": "#5491b5",
    "brandSoft": "#17303f",
    "brandTint": "#121e27",
    "onBrandSoft": "#80b1cc",
    "accent": "#e87722",
    "accentSoft": "#33240f",
    "accentTint": "#211809",
    "accentStrong": "#f7a855",
    "accentCta": "#e87722",
    "textOnAccentCta": "#ffffff",
    "evergreen": "#2e7d52",
    "evergreenSoft": "#143024",
    "evergreenTint": "#0f2018",
    "onSuccessSoft": "#6fb78d",
    "canvas": "#0f1519",
    "surfaceCard": "#1a232b",
    "surfaceSunken": "#10171d",
    "surfaceInverse": "#eef1f3",
    "textStrong": "#f4f7f9",
    "textBody": "#d3dbe1",
    "textMuted": "#9aa8b2",
    "textFaint": "#71808b",
    "textOnBrand": "#ffffff",
    "textOnAccent": "#182026",
    "textOnDanger": "#182026",
    "textLink": "#80b1cc",
    "border": "#2c3740",
    "borderStrong": "#3f4b54",
    "divider": "#222c33",
    "success": "#2e7d52",
    "successSoft": "#143024",
    "warning": "#e87722",
    "warningSoft": "#33240f",
    "danger": "#ef7683",
    "dangerSoft": "#3a1c22",
    "info": "#3c7499",
    "infoSoft": "#17303f",
    "pikaGolden": "#ffcd45",
    "focusRing": "rgba(128, 177, 204, 0.55)",
    "overlayScrim": "rgba(0, 0, 0, 0.55)",
    "overlayDark": "rgba(0, 0, 0, 0.72)",
    "overlayGlass": "rgba(20, 28, 35, 0.82)",
    "overlayTint": "rgba(60, 116, 153, 0.10)",
    "skeletonBase": "#1f2a32",
    "skeletonShine": "#2a3742"
  }
} as const;

export type Tokens = typeof tokens;
