-- 1.5 — seed from Azure /languages?scope=dictionary (fetched live 2026-07-04).
-- All dictionary pairs are X<->en (16 §1). enrich=true marks launch enrichment pairs.
insert into public.languages (code, name, native_name, dir, dictionary_with_en, enrich) values
('en','English','English','ltr',true,true),
('es','Spanish','Español','ltr',true,true),
('af','Afrikaans','Afrikaans','ltr',true,false),
('ar','Arabic','العربية','rtl',true,false),
('bg','Bulgarian','Български','ltr',true,false),
('bn','Bangla','বাংলা','ltr',true,false),
('bs','Bosnian','Bosanski','ltr',true,false),
('ca','Catalan','Català','ltr',true,false),
('cs','Czech','Čeština','ltr',true,false),
('cy','Welsh','Cymraeg','ltr',true,false),
('da','Danish','Dansk','ltr',true,false),
('de','German','Deutsch','ltr',true,false),
('el','Greek','Ελληνικά','ltr',true,false),
('et','Estonian','Eesti','ltr',true,false),
('fa','Persian','فارسی','rtl',true,false),
('fi','Finnish','Suomi','ltr',true,false),
('fr','French','Français','ltr',true,false),
('he','Hebrew','עברית','rtl',true,false),
('hi','Hindi','हिन्दी','ltr',true,false),
('hr','Croatian','Hrvatski','ltr',true,false),
('hu','Hungarian','Magyar','ltr',true,false),
('id','Indonesian','Indonesia','ltr',true,false),
('is','Icelandic','Íslenska','ltr',true,false),
('it','Italian','Italiano','ltr',true,false),
('ja','Japanese','日本語','ltr',true,false),
('ko','Korean','한국어','ltr',true,false),
('lt','Lithuanian','Lietuvių','ltr',true,false),
('lv','Latvian','Latviešu','ltr',true,false),
('ms','Malay','Melayu','ltr',true,false),
('mt','Maltese','Malti','ltr',true,false),
('mww','Hmong Daw','Hmong Daw','ltr',true,false),
('nb','Norwegian','Norsk Bokmål','ltr',true,false),
('nl','Dutch','Nederlands','ltr',true,false),
('pl','Polish','Polski','ltr',true,false),
('pt','Portuguese (Brazil)','Português (Brasil)','ltr',true,false),
('ro','Romanian','Română','ltr',true,false),
('ru','Russian','Русский','ltr',true,false),
('sk','Slovak','Slovenčina','ltr',true,false),
('sl','Slovenian','Slovenščina','ltr',true,false),
('sr-Latn','Serbian (Latin)','Srpski (latinica)','ltr',true,false),
('sv','Swedish','Svenska','ltr',true,false),
('sw','Swahili','Kiswahili','ltr',true,false),
('ta','Tamil','தமிழ்','ltr',true,false),
('th','Thai','ไทย','ltr',true,false),
('tlh-Latn','Klingon (Latin)','Klingon (Latin)','ltr',true,false),
('tr','Turkish','Türkçe','ltr',true,false),
('uk','Ukrainian','Українська','ltr',true,false),
('ur','Urdu','اردو','rtl',true,false),
('vi','Vietnamese','Tiếng Việt','ltr',true,false),
('zh-Hans','Chinese Simplified','中文 (简体)','ltr',true,false);;
